name: Build LineageOS ROM


on:
  workflow_dispatch:
    inputs:
      SYNC_URL:
        description: 'SYNC_URL'
        required: true
        default: 'https://github.com/LineageOS/android.git'
      MANIFEST_BRANCH:
        description: 'MANIFEST_BRANCH'
        required: true
        default: 'lineage-22.1'
      DEVICE_TREE_URL:
        description: 'DEVICE_TREE_URL'
        required: true
        default: 'https://github.com/Neoteric-OS/android_device_xiaomi_aurora'
      DEVICE_TREE_BRANCH:
        description: 'DEVICE_TREE_BRANCH'
        required: true
        default: 'vic'
      DEVICE_PATH:
        description: 'DEVICE_PATH'
        required: true
        default: 'device/xiaomi/aurora'
      COMMON_TREE_URL:
        description: 'COMMON_TREE_URL (if no common tree, leave blank)'
        required: false
      COMMON_PATH:
        description: 'COMMON_PATH (if no common tree, leave blank)'
        required: false
      DEVICE_NAME:
        description: 'DEVICE_NAME'
        required: true
        default: 'aurora'
      MAKEFILE_NAME:
        description: 'MAKEFILE_NAME'
        required: true
        default: 'lineage_aurora'

jobs:
  build-lineageos:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check if sender is repository owner
      if: github.event.repository.owner.login == github.event.sender.login
      run: |
        echo "Sender is the repository owner"
    - name: Not the repository owner
      if: github.event.repository.owner.login != github.event.sender.login
      run: |
        echo "Sender is not the repository owner"
        exit 1

    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Initialize workspace
      run: |
        mkdir workspace
        cd workspace
        echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
      id: pwd

    - name: Prepare the build environment
      run: |
        sudo apt install git aria2 openjdk-21-jdk-headless -y
        export JAVA_HOME=$(readlink -f $(which java))
        git clone https://gitlab.com/OrangeFox/misc/scripts
        cd scripts
        sudo bash setup/android_build_env.sh
        sed -i 's/cd -/cd ../g' setup/install_android_sdk.sh
        sudo bash setup/install_android_sdk.sh
        mkdir ${{ steps.pwd.outputs.workspace-folder }}/ccache
        export USE_CCACHE=1
        export CCACHE_DIR=${{ steps.pwd.outputs.workspace-folder }}/ccache/
        ccache -M 50G
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Clone and sync Lineage sources
      run: |
        cd ${{ steps.pwd.outputs.workspace-folder }}
        mkdir lineage
        cd lineage
        repo init -u ${{ github.event.inputs.SYNC_URL }} -b ${{ github.event.inputs.MANIFEST_BRANCH }} --git-lfs
        repo sync
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Clone device tree
      run: |
        cd ${{ steps.pwd.outputs.workspace-folder }}/lineage/
        git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Clone common tree
      if: |
        github.event.inputs.COMMON_TREE_URL != null
        && github.event.inputs.COMMON_PATH != null
      run: |
        cd ${{ steps.pwd.outputs.workspace-folder }}/lineage/
        git clone ${{ github.event.inputs.COMMON_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.COMMON_PATH }}
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Build Lineage ROM
      run: |
        cd ${{ steps.pwd.outputs.workspace-folder }}/lineage/
        . build/envsetup.sh
        export USE_CCACHE=1
        export CCACHE_DIR=ccache/
        ccache -M 50G
        lunch ${{ github.event.inputs.MAKEFILE_NAME }}
        m otapackage
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}
      continue-on-error: true

    - name: Check the output directory before uploading
      run: |
        ls -al ${{ steps.pwd.outputs.workspace-folder }}/lineage/out/target/product/
        echo
        ls -al ${{ steps.pwd.outputs.workspace-folder }}/lineage/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ steps.pwd.outputs.workspace-folder }}/lineage/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/*.zip
        name: ${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          Manifest: ${{ github.event.inputs.MANIFEST_BRANCH }}
          Device: ${{ github.event.inputs.DEVICE_NAME }}
          Target: ${{ github.event.inputs.BUILD_TARGET }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
